name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: npm run quality

      - name: Build application
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        # Remove this condition once secrets are configured
        if: false
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./

      - name: Deployment info
        run: |
          echo "🚀 Build completed successfully!"
          echo ""
          echo "📝 To enable automatic Vercel deployment:"
          echo "1. Create a Vercel project for your repository"
          echo "2. Add these secrets to your GitHub repository:"
          echo "   - VERCEL_TOKEN: Your Vercel token"
          echo "   - VERCEL_ORG_ID: Your Vercel organization ID"  
          echo "   - VERCEL_PROJECT_ID: Your Vercel project ID"
          echo "3. Change 'if: false' to 'if: true' in the deploy step above"
          echo ""
          echo "📚 See TEMPLATE_SETUP.md for detailed instructions"
